<template>
  <article class="content-page">
    <h1 class="heading">THE HISTORY OF TIME-OUT</h1><br>

<h2>THE BIRTH OF TIME-OUT</h2>

<p>Time-Out Amusement Center was started by an entrepreneur named Tico Bonomo. Tico was a candy manufacturer and the owner of Bonomo's Turkish Taffy fame, one of the largest hard candy manufacturers on the East Coast. In 1970 Tico sold the upstate New York taffy company to Tootsie Roll, and he began looking for another commercial venture to start up.</p>
<p>In the late 1960s the idea of a mall arcade as we know it today didn't exist yet. Video games didn't exist either. Primitive coin-operated electro mechanical games were just beginning to creep into retail stores on the eastern seaboard. These primitive games were purely mechanical machines that worked via motors, relays, and projectors. But seeing the nascent electromechanical games beginning to accumulate in various retail stores, Tico excitedly realized that an entire store full of coin-operated games in a shopping mall could perhaps be a successful business and something that hadn't been done before.</p>
<p>In 1970, Tico opened the first Time-Out Family Amusement Center in the Northway Mall in Colonie, New York. The arcade was a large success. In fact, to Tico's surprise, the arcade was an even larger success than the Taffy company he had just sold. Encouraged by the good fortune, Tico opened a few more of his Amusement Centers.</p>
<p>Nobody could predict what was to happen next, but Tico's timing was perfect, and he and his small arcade chain were perfectly positioned for the explosion that was about the happen. In 1972, Pong hit the scene, and customers flooded into Tico's Time-Out Amusement Centers and unleashed a tidal wave of quarters that nobody could have foreseen. Tico was in the exactly right place at exactly the right time.</p>

<h2>A PERFECT STORM</h2>

<p>Riding the overwhelming popularity of Pong and the numerous copycat games that followed, by the year 1975 Tico had expanded his coin-op empire to a dozen locations. By 1978, there were twenty locations, and it wasn't over yet. 1978 was the year Space Invaders hit the US, and Tico and his quickly growing chain of arcades rode a second huge wave of expansion and growth triggered by the popularity of Space Invaders.</p>
<p>Not only was the video game industry exploding, shopping mall construction was also going through a huge period of expansion. For Tico and his Time-Out chain, this created nothing less than a Perfect Storm of opportunity. The "Mall Arcade" was a sensation. New malls were opening everywhere, and each new mall would open another chance for Tico to install one of his successful arcade centers. The explosion of growth on several fronts drove the video game manufacturers, all competing for the customer's quarters, to create more sophisticated and fancier video games, which in turn created a vicious cycle driving the growth of the Mall Arcade.</p>
<p>Working at the Sunrise Mall Time-Out in 1981 in Massapequa, NY, Geoffrey Kovar remembers the employee uniform. “Blue buttoned-down shirt, black slacks, 6-slot coin dispenser on the belt with not one but two quick-release slots to dispense 4 quarters with a single press, faux cloth badge, the works.”. He describes a typical early 80s working environment: “The usual layout of the Time Outs I saw had two rear doors, one in each back corner, opening inward, and which generally had a small window or even a peephole (like a front door). In the one I worked at the one on the right led to the setup/repair room. Lots of arcade machines open, in various states of repair, or in crates, and it took up probably 2/3 of the back area. The one on the left led to a short hallway. Two doors from there, one a fire door to the mall hallway, and one to the right, leading to the office/vault. There was a big safe in there with tons of money, and also several secure drawers for each of the people on shift. Usual work drawer was $500, in quarters, except for a bit of paper to make change. First job I ever had to get bonded to work at, and had to take a polygraph test. Oh, and none of this stuff about tokens. We used quarters, baby! And to track the usage of slugs and free games we gave out, there was a bin of quarters painted red (red nail polish, actually) in the office that we dipped into when necessary."</p>
<p>Over the next few years, the machines got better and flashier, the audience for video games ballooned, and new arcade locations were opening at a furious pace. Every mall had an arcade - sometimes more than one. The industry was at its peak at this point, producing its seminal games like Asteroids, Pacman, Defender, Galaga, Battlezone, Tempest, and other machines that sucked video game players into arcades like a giant ever-expanding whirlpool. Video games and arcades were everywhere, and Time-Out Amusement Center was at the forefront of the industry.</p>

<h2>THE DEATH OF THE ARCADE</h2>

<p>When the arcade bubble finally burst, it burst big. Arcades across the country either boarded up and went out of business, or they merged to stay alive. Time-Out took the opportunity to buy out Sega's West Coast chain of 13 arcades. Time-Out rose from the ashes of the devastated arcade business to ride the wave of popularity in a new type of arcade machine - the redemption game. Redemption games, such as crane machines that hand out toy prizes, allowed Time-Out to stay afloat. By 1987, they had 70 stores.</p>
<p>Around 1992, the Time-Out chain was purchased by Edison Brothers’ Mall Entertainment Division. Edison Brothers Inc was a large clothing and shoe giant based out of St. Louis. John Beck, a former employee, recalls: “Edison had bought another arcade company before Time-Out, and tried to change the way Time-Out did business. Edison used the company as a cash cow, robbing all of the profits to offset their weak sales, as I understand it”. Edison owned several arcade chains at the peak of their amusement center days, which included Space Port, Station Break, and of course Time-Out. They filed for Chapter 11 bankruptcy in 1995. The subsequent restructuring saw them dissolving their Mall Entertainment division and Time-Out was sold again, this time to Namco LTD. Namco already owned a popular chain of arcades called Cyberstation when they acquired Time-Out. Jim Miller, who worked for Cyberstation at the time, remembers when Time-Out was taken over by Namco. “Time-Out corporate all got pink slips I believe”, Jim says. “All I ever knew of the Time Outs were the boxes of stuff that ended up in the warehouse. Eventually they pulled in a couple dumpsters from the street and filled them up. I grabbed what I could. Probably a lot of history ended up in a landfill but it was just receipts and accounting stuff I bet.”</p>
<p>These days many people have never heard of Time-Out, and I suspect they primarily existed on the East Coast. Their corporate headquarters were based in Fairfax Virginia before they were bought out, which explains the East Coast focus of the chain. Still I am led to believe that there were, at their peak, one of the largest arcade chains in the USA, with locations extending to Puerto Rico and St. Thomas in the Virgin Islands. Some locations still exist today as a Namco-operated / Time-Out branded Cyberstations.</p>
<p>Tico ultimately retired in Northern Virginia with his family. I was hoping to meet him in person to thank him for his contributions and perhaps to interview him but learned that, sadly, he passed away in 1999. I'm sorry I never got to meet you Tico.</p>
  </article>
</template>

<script>
export default {
  name: 'History'
}
</script>

